# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_control_gui.ui'
#
# Created: Thu Apr 24 15:19:45 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Server_control(object):
    def setupUi(self, Server_control):
        Server_control.setObjectName(_fromUtf8("Server_control"))
        Server_control.resize(800, 555)
        self.frame_command_input = QtGui.QFrame(Server_control)
        self.frame_command_input.setGeometry(QtCore.QRect(0, 0, 800, 555))
        self.frame_command_input.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_command_input.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_command_input.setObjectName(_fromUtf8("frame_command_input"))
        self.frame_command_input_1 = QtGui.QFrame(self.frame_command_input)
        self.frame_command_input_1.setGeometry(QtCore.QRect(10, 10, 780, 535))
        self.frame_command_input_1.setFrameShape(QtGui.QFrame.Box)
        self.frame_command_input_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_command_input_1.setObjectName(_fromUtf8("frame_command_input_1"))
        self.frame_command_input_1_groupBox_1 = QtGui.QGroupBox(self.frame_command_input_1)
        self.frame_command_input_1_groupBox_1.setGeometry(QtCore.QRect(10, 10, 760, 60))
        self.frame_command_input_1_groupBox_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_1"))
        self.frame_command_input_1_groupBox_1_label_1 = QtGui.QLabel(self.frame_command_input_1_groupBox_1)
        self.frame_command_input_1_groupBox_1_label_1.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.frame_command_input_1_groupBox_1_label_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_1_label_1"))
        self.frame_command_input_1_groupBox_1_lineEdit_1 = QtGui.QLineEdit(self.frame_command_input_1_groupBox_1)
        self.frame_command_input_1_groupBox_1_lineEdit_1.setGeometry(QtCore.QRect(70, 30, 170, 20))
        self.frame_command_input_1_groupBox_1_lineEdit_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_command_input_1_groupBox_1_lineEdit_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_1_lineEdit_1"))
        self.frame_command_input_1_groupBox_1_lineEdit_2 = QtGui.QLineEdit(self.frame_command_input_1_groupBox_1)
        self.frame_command_input_1_groupBox_1_lineEdit_2.setGeometry(QtCore.QRect(310, 30, 130, 20))
        self.frame_command_input_1_groupBox_1_lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_command_input_1_groupBox_1_lineEdit_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_1_lineEdit_2"))
        self.frame_command_input_1_groupBox_1_label_2 = QtGui.QLabel(self.frame_command_input_1_groupBox_1)
        self.frame_command_input_1_groupBox_1_label_2.setGeometry(QtCore.QRect(250, 30, 61, 20))
        self.frame_command_input_1_groupBox_1_label_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_1_label_2"))
        self.frame_command_input_1_groupBox_1_lineEdit_3 = QtGui.QLineEdit(self.frame_command_input_1_groupBox_1)
        self.frame_command_input_1_groupBox_1_lineEdit_3.setGeometry(QtCore.QRect(495, 30, 130, 20))
        self.frame_command_input_1_groupBox_1_lineEdit_3.setEchoMode(QtGui.QLineEdit.Password)
        self.frame_command_input_1_groupBox_1_lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_command_input_1_groupBox_1_lineEdit_3.setObjectName(_fromUtf8("frame_command_input_1_groupBox_1_lineEdit_3"))
        self.frame_command_input_1_groupBox_1_label_3 = QtGui.QLabel(self.frame_command_input_1_groupBox_1)
        self.frame_command_input_1_groupBox_1_label_3.setGeometry(QtCore.QRect(450, 30, 45, 20))
        self.frame_command_input_1_groupBox_1_label_3.setObjectName(_fromUtf8("frame_command_input_1_groupBox_1_label_3"))
        self.frame_command_input_1_groupBox_1_button_1 = QtGui.QPushButton(self.frame_command_input_1_groupBox_1)
        self.frame_command_input_1_groupBox_1_button_1.setGeometry(QtCore.QRect(640, 30, 110, 20))
        self.frame_command_input_1_groupBox_1_button_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_1_button_1"))
        self.frame_command_input_1_groupBox_2 = QtGui.QGroupBox(self.frame_command_input_1)
        self.frame_command_input_1_groupBox_2.setGeometry(QtCore.QRect(10, 70, 260, 460))
        self.frame_command_input_1_groupBox_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_2"))
        self.frame_command_input_1_groupBox_2_tableView_1 = QtGui.QTableView(self.frame_command_input_1_groupBox_2)
        self.frame_command_input_1_groupBox_2_tableView_1.setGeometry(QtCore.QRect(10, 30, 240, 391))
        self.frame_command_input_1_groupBox_2_tableView_1.setDragEnabled(True)
        self.frame_command_input_1_groupBox_2_tableView_1.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.frame_command_input_1_groupBox_2_tableView_1.setAlternatingRowColors(True)
        self.frame_command_input_1_groupBox_2_tableView_1.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.frame_command_input_1_groupBox_2_tableView_1.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.frame_command_input_1_groupBox_2_tableView_1.setSortingEnabled(True)
        self.frame_command_input_1_groupBox_2_tableView_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_2_tableView_1"))
        self.frame_command_input_1_groupBox_2_tableView_1.horizontalHeader().setStretchLastSection(True)
        self.frame_command_input_1_groupBox_2_pushButton_1 = QtGui.QPushButton(self.frame_command_input_1_groupBox_2)
        self.frame_command_input_1_groupBox_2_pushButton_1.setGeometry(QtCore.QRect(40, 430, 80, 23))
        self.frame_command_input_1_groupBox_2_pushButton_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_2_pushButton_1"))
        self.frame_command_input_1_groupBox_2_pushButton_2 = QtGui.QPushButton(self.frame_command_input_1_groupBox_2)
        self.frame_command_input_1_groupBox_2_pushButton_2.setGeometry(QtCore.QRect(135, 430, 80, 23))
        self.frame_command_input_1_groupBox_2_pushButton_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_2_pushButton_2"))
        self.frame_command_input_1_groupBox_3 = QtGui.QGroupBox(self.frame_command_input_1)
        self.frame_command_input_1_groupBox_3.setGeometry(QtCore.QRect(280, 70, 490, 460))
        self.frame_command_input_1_groupBox_3.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3"))
        self.frame_command_input_1_groupBox_3_textEdit_2 = QtGui.QTextEdit(self.frame_command_input_1_groupBox_3)
        self.frame_command_input_1_groupBox_3_textEdit_2.setGeometry(QtCore.QRect(0, 212, 481, 241))
        self.frame_command_input_1_groupBox_3_textEdit_2.setReadOnly(True)
        self.frame_command_input_1_groupBox_3_textEdit_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_textEdit_2"))
        self.frame_command_input_1_groupBox_3_label_5 = QtGui.QLabel(self.frame_command_input_1_groupBox_3)
        self.frame_command_input_1_groupBox_3_label_5.setGeometry(QtCore.QRect(0, 190, 120, 20))
        self.frame_command_input_1_groupBox_3_label_5.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_label_5"))
        self.frame_command_input_1_groupBox_3_tabWidget_1 = QtGui.QTabWidget(self.frame_command_input_1_groupBox_3)
        self.frame_command_input_1_groupBox_3_tabWidget_1.setGeometry(QtCore.QRect(240, 30, 240, 155))
        self.frame_command_input_1_groupBox_3_tabWidget_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_4 = QtGui.QPushButton(self.tab)
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_4.setGeometry(QtCore.QRect(155, 92, 75, 23))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_4.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1_pushButton_4"))
        self.frame_command_input_1_groupBox_3_tabWidget_1_textEdit_2 = QtGui.QTextEdit(self.tab)
        self.frame_command_input_1_groupBox_3_tabWidget_1_textEdit_2.setGeometry(QtCore.QRect(5, 34, 225, 51))
        self.frame_command_input_1_groupBox_3_tabWidget_1_textEdit_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1_textEdit_2"))
        self.frame_command_input_1_groupBox_3_tabWidget_1_label_2 = QtGui.QLabel(self.tab)
        self.frame_command_input_1_groupBox_3_tabWidget_1_label_2.setGeometry(QtCore.QRect(5, 7, 171, 20))
        self.frame_command_input_1_groupBox_3_tabWidget_1_label_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1_label_2"))
        self.frame_command_input_1_groupBox_3_tabWidget_1.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_1 = QtGui.QPushButton(self.tab_2)
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_1.setGeometry(QtCore.QRect(155, 92, 75, 23))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1_pushButton_1"))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_2.setGeometry(QtCore.QRect(155, 5, 75, 23))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1_pushButton_2"))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_3.setGeometry(QtCore.QRect(70, 92, 75, 23))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_3.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1_pushButton_3"))
        self.frame_command_input_1_groupBox_3_tabWidget_1_textEdit_1 = QtGui.QTextEdit(self.tab_2)
        self.frame_command_input_1_groupBox_3_tabWidget_1_textEdit_1.setGeometry(QtCore.QRect(5, 35, 225, 50))
        self.frame_command_input_1_groupBox_3_tabWidget_1_textEdit_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1_textEdit_1"))
        self.frame_command_input_1_groupBox_3_tabWidget_1_label_1 = QtGui.QLabel(self.tab_2)
        self.frame_command_input_1_groupBox_3_tabWidget_1_label_1.setGeometry(QtCore.QRect(5, 7, 151, 20))
        self.frame_command_input_1_groupBox_3_tabWidget_1_label_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_3_tabWidget_1_label_1"))
        self.frame_command_input_1_groupBox_3_tabWidget_1.addTab(self.tab_2, _fromUtf8(""))
        self.frame_command_input_1_groupBox_4_tabWidget_1 = QtGui.QTabWidget(self.frame_command_input_1_groupBox_3)
        self.frame_command_input_1_groupBox_4_tabWidget_1.setGeometry(QtCore.QRect(0, 30, 240, 155))
        self.frame_command_input_1_groupBox_4_tabWidget_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_4_tabWidget_1"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.frame_command_input_1_groupBox_4_lineEdit_3 = QtGui.QLineEdit(self.tab_3)
        self.frame_command_input_1_groupBox_4_lineEdit_3.setGeometry(QtCore.QRect(80, 80, 140, 20))
        self.frame_command_input_1_groupBox_4_lineEdit_3.setReadOnly(True)
        self.frame_command_input_1_groupBox_4_lineEdit_3.setObjectName(_fromUtf8("frame_command_input_1_groupBox_4_lineEdit_3"))
        self.frame_command_input_1_groupBox_4_label_1 = QtGui.QLabel(self.tab_3)
        self.frame_command_input_1_groupBox_4_label_1.setGeometry(QtCore.QRect(20, 20, 61, 20))
        self.frame_command_input_1_groupBox_4_label_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_4_label_1"))
        self.frame_command_input_1_groupBox_4_lineEdit_1 = QtGui.QLineEdit(self.tab_3)
        self.frame_command_input_1_groupBox_4_lineEdit_1.setGeometry(QtCore.QRect(80, 20, 140, 20))
        self.frame_command_input_1_groupBox_4_lineEdit_1.setReadOnly(True)
        self.frame_command_input_1_groupBox_4_lineEdit_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_4_lineEdit_1"))
        self.frame_command_input_1_groupBox_4_label_2 = QtGui.QLabel(self.tab_3)
        self.frame_command_input_1_groupBox_4_label_2.setGeometry(QtCore.QRect(20, 50, 61, 20))
        self.frame_command_input_1_groupBox_4_label_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_4_label_2"))
        self.frame_command_input_1_groupBox_4_lineEdit_2 = QtGui.QLineEdit(self.tab_3)
        self.frame_command_input_1_groupBox_4_lineEdit_2.setGeometry(QtCore.QRect(80, 50, 140, 20))
        self.frame_command_input_1_groupBox_4_lineEdit_2.setReadOnly(True)
        self.frame_command_input_1_groupBox_4_lineEdit_2.setObjectName(_fromUtf8("frame_command_input_1_groupBox_4_lineEdit_2"))
        self.frame_command_input_1_groupBox_4_label_3 = QtGui.QLabel(self.tab_3)
        self.frame_command_input_1_groupBox_4_label_3.setGeometry(QtCore.QRect(20, 80, 61, 20))
        self.frame_command_input_1_groupBox_4_label_3.setObjectName(_fromUtf8("frame_command_input_1_groupBox_4_label_3"))
        self.frame_command_input_1_groupBox_4_tabWidget_1.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1 = QtGui.QTableView(self.tab_4)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.setGeometry(QtCore.QRect(5, 5, 225, 110))
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.setDragEnabled(True)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.setAlternatingRowColors(True)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.setSortingEnabled(True)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.setObjectName(_fromUtf8("frame_command_input_1_groupBox_4_tabWidget_1_tableView_1"))
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.horizontalHeader().setDefaultSectionSize(80)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.horizontalHeader().setMinimumSectionSize(30)
        self.frame_command_input_1_groupBox_4_tabWidget_1_tableView_1.horizontalHeader().setStretchLastSection(True)
        self.frame_command_input_1_groupBox_4_tabWidget_1.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Server_control)
        self.frame_command_input_1_groupBox_3_tabWidget_1.setCurrentIndex(0)
        self.frame_command_input_1_groupBox_4_tabWidget_1.setCurrentIndex(0)
        QtCore.QObject.connect(self.frame_command_input_1_groupBox_1_button_1, QtCore.SIGNAL(_fromUtf8("clicked()")), Server_control.add_server_list)
        QtCore.QObject.connect(self.frame_command_input_1_groupBox_2_pushButton_1, QtCore.SIGNAL(_fromUtf8("clicked()")), Server_control.delete_choose)
        QtCore.QObject.connect(self.frame_command_input_1_groupBox_2_pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Server_control.add_task)
        QtCore.QObject.connect(self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_1, QtCore.SIGNAL(_fromUtf8("clicked()")), Server_control.task_run_2)
        QtCore.QObject.connect(self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Server_control.task_read)
        QtCore.QObject.connect(self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Server_control.task_run_1)
        QtCore.QObject.connect(self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Server_control.task_save)
        QtCore.QMetaObject.connectSlotsByName(Server_control)

    def retranslateUi(self, Server_control):
        Server_control.setWindowTitle(_translate("Server_control", "Server_control", None))
        self.frame_command_input_1_groupBox_1.setTitle(_translate("Server_control", "服务器新增栏", None))
        self.frame_command_input_1_groupBox_1_label_1.setText(_translate("Server_control", "IP地址：", None))
        self.frame_command_input_1_groupBox_1_lineEdit_1.setPlaceholderText(_translate("Server_control", "格式：xxx.xxx.xxx.xxx", None))
        self.frame_command_input_1_groupBox_1_lineEdit_2.setPlaceholderText(_translate("Server_control", "格式：至少4位", None))
        self.frame_command_input_1_groupBox_1_label_2.setText(_translate("Server_control", "用户名：", None))
        self.frame_command_input_1_groupBox_1_lineEdit_3.setPlaceholderText(_translate("Server_control", "格式：至少6位", None))
        self.frame_command_input_1_groupBox_1_label_3.setText(_translate("Server_control", "密码：", None))
        self.frame_command_input_1_groupBox_1_button_1.setText(_translate("Server_control", "加入服务器列表", None))
        self.frame_command_input_1_groupBox_2.setTitle(_translate("Server_control", "服务器列表栏", None))
        self.frame_command_input_1_groupBox_2_pushButton_1.setText(_translate("Server_control", "删除选中行", None))
        self.frame_command_input_1_groupBox_2_pushButton_2.setText(_translate("Server_control", "加入任务栏", None))
        self.frame_command_input_1_groupBox_3.setTitle(_translate("Server_control", "任务创建栏", None))
        self.frame_command_input_1_groupBox_3_label_5.setText(_translate("Server_control", "执行任务情况：", None))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_4.setText(_translate("Server_control", "执行任务", None))
        self.frame_command_input_1_groupBox_3_tabWidget_1_label_2.setText(_translate("Server_control", "输入脚本路径执行任务：", None))
        self.frame_command_input_1_groupBox_3_tabWidget_1.setTabText(self.frame_command_input_1_groupBox_3_tabWidget_1.indexOf(self.tab), _translate("Server_control", "从脚本文件执行", None))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_1.setText(_translate("Server_control", "执行任务", None))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_2.setText(_translate("Server_control", "导入脚本", None))
        self.frame_command_input_1_groupBox_3_tabWidget_1_pushButton_3.setText(_translate("Server_control", "保存脚本", None))
        self.frame_command_input_1_groupBox_3_tabWidget_1_label_1.setText(_translate("Server_control", "输入命令行执行任务：", None))
        self.frame_command_input_1_groupBox_3_tabWidget_1.setTabText(self.frame_command_input_1_groupBox_3_tabWidget_1.indexOf(self.tab_2), _translate("Server_control", "从命令行执行", None))
        self.frame_command_input_1_groupBox_4_label_1.setText(_translate("Server_control", "IP地址：", None))
        self.frame_command_input_1_groupBox_4_label_2.setText(_translate("Server_control", "用户名：", None))
        self.frame_command_input_1_groupBox_4_label_3.setText(_translate("Server_control", "密码：", None))
        self.frame_command_input_1_groupBox_4_tabWidget_1.setTabText(self.frame_command_input_1_groupBox_4_tabWidget_1.indexOf(self.tab_3), _translate("Server_control", "选择单服务器", None))
        self.frame_command_input_1_groupBox_4_tabWidget_1.setTabText(self.frame_command_input_1_groupBox_4_tabWidget_1.indexOf(self.tab_4), _translate("Server_control", "选择多服务器", None))

